-- Generated by scripts/hypr2lua.
-- Source: omarchy-biscuit-de-mar-dark-theme/hyprland.conf

local activeBorderColor = {
  colors = { "rgb(AE3F82)", "rgb(AE3F82)", "rgb(AE3F82)", "rgb(AE3F82)", "rgb(E39C45)", "rgb(AE3F82)", "rgb(AE3F82)", "rgb(AE3F82)" },
  angle = 35,
}
local inactiveBorderColor = "rgba(725a5acc)"

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
      inactive_border = inactiveBorderColor,
    },
  },
  group = {
    col = {
      border_active = activeBorderColor,
      border_inactive = inactiveBorderColor,
    },
  },
  decoration = {
    blur = {},
  },
})
